language: node_js

node_js:
  - "6"
  - "8"

# env:
#   - CONTEXT=XXX

# before_install:
#   - stty columns 120

install:
  - npm install

script:
  - npm test

# sudo: false

# notifications:
#   email: false
